### ISSUE TITLE
_site folder is not generated at all after updating docfx.console package from 2.15.5 to 2.16.0

### ISSUE THREAD

**Issue by ThomasEnioKohler** [dotnet/docfx#1565]
### _site folder is not created
After updating from 2.15.6 to 2.16.0 with no change in project or project structure the _site folder is not generated anymore.

### Functional impact
no generation of the _site folder and therefore no web site available 

### Minimal repro steps
Update nuget package from version 2.15.6 to 2.16.0

### Expected result
_site folder has to be generated on build

### Actual result
It seems that docfx doesn't run at all on build

### Further technical details
none

**Comment by hellosnow** [comment]
@ThomasEnioKohler I tried to run docfx 2.16.0 against [docfx-seed](https://github.com/docascode/docfx-seed), and I can see the _site folder, could you share your docfx.json with us? Did you include "dest": "_site" in it?

**Comment by ThomasEnioKohler** [comment]
I did use the default docfx.json file generated when the docfx.console package was added.

Please find below the json file.

[docfx.zip](https://github.com/dotnet/docfx/files/929731/docfx.zip)

**Comment by vicancy** [comment]
2.16 upgrades to use net46. Visual Studio 2017 with .NET Core cross-platform development toolset is a prerequisite, @ThomasEnioKohler what is your running env?

**Comment by vicancy** [comment]
could you run with `--loglevel verbose` and provide the log?

**Comment by ThomasEnioKohler** [comment]
I run Visual Studio 2017 with .Net Core development toolset installed.

![image](https://cloud.githubusercontent.com/assets/25221063/25165756/3806c8b8-24d8-11e7-846d-5a8ade52c013.png)

How can I run with --loglevel verbose when building from Visual Studio?

**Comment by ThomasEnioKohler** [comment]
I do run Visual Studio with its latest release:
![image](https://cloud.githubusercontent.com/assets/25221063/25166087/e789369e-24d9-11e7-95e7-4a5b3656b193.png)

**Comment by ThomasEnioKohler** [comment]
and enclosed the output of a diagnostic build

[build.txt](https://github.com/dotnet/docfx/files/932011/build.txt)

**Comment by vicancy** [comment]
Try running in command line:
`C:\NuGetPackages\docfx.console.2.16.0\tools\docfx.exe docfx.json --loglevel verbose`

**Comment by ThomasEnioKohler** [comment]
running with the command line the _site is generated properly. it doesn't work from Visual Studio only

**Comment by justhoma** [comment]
We are experiencing exactly the same issue. We noticed that the "build" folder is missing from the 2.16.2 nuGet package which would explain why the site is not being generated. Is there an issue with the package or do we need to do something else to get this to work?

**Comment by LordZoltan** [comment]
I had an issue upgrading from 2.15 to 2.16 whereby the `.targets` imports in the .csproj file were removed but not re-added.  I re-added this import into the project file but noticed, whilst manually adding it, that the new imports looks like this:

```xml
<Import Project="..\..\packages\docfx.console.2.16.2\tools\docfx.console.targets" Condition="Exists('..\..\packages\docfx.console.2.16.2\tools\docfx.console.targets')" />
```

Whereas it previously looked like this:

```xml
<Import Project="..\..\packages\docfx.console.2.x.y\build\docfx.console.targets" Condition="Exists('..\..\packages\docfx.console.2.x.y\build\docfx.console.targets')" />
```
I now have it running again on build - but it's not generating *any* metadata for my project, Rezolver.

[Here is the docfx.json](https://github.com/ZolutionSoftware/Rezolver/blob/c35a25156ca5f2af76775d0153972d6a314187a1/doc/Rezolver.Documentation/docfx.json), altered according to the 2.16.x release doc; and [here is the project file it's pointing at](https://github.com/ZolutionSoftware/Rezolver/blob/c35a25156ca5f2af76775d0153972d6a314187a1/src/Rezolver/Rezolver.csproj).

And, right at the beginning of the log output from the docfx command line - I see this:

```
3>  [17-04-20 10:53:19.753]Warning:Cache for E:/Github/Rezolver/src/Rezolver/Rezolver.csproj in E:\Github\Rezolver\src\Rezolver\obj\xdoc\cache\final\1285379993 is corrupted
3>  [17-04-20 10:53:19.753]Warning:No metadata is generated for Rezolver.
```
If I clean the `E:\Github\Rezolver\src\Rezolver\obj\xdoc\cache` folder and rebuild, I no longer get a message about corruption - but I still get a message telling me that no metadata is generated.

I have been using a dummy `.csproj` file (called `rezolver-docfx.csproj` - but it doesn't auto-link MSDN types (like `System.Linq.Expressions.Expression`) via the xref maps for any `<see cref="blah"` XMLDoc comments.  And, in any case, that no longer works either because I get a `TypeLoadException` logged by docfx after doing a build!

**Comment by vicancy** [comment]
Looks like a bug in packaging msbuild.console package, will take a look. Thanks for reporting the issue

**Comment by LordZoltan** [comment]
As mentioned at the end of my last comment, when trying to use [a 'standard' csproj](https://github.com/ZolutionSoftware/Rezolver/blob/c35a25156ca5f2af76775d0153972d6a314187a1/src/Rezolver/rezolver-docfx.csproj) as the reference project in the `docfx.json` file (as I did before after moving to `project.json` to the new msbuild format), I get a `TypeLoadException` - [here's the build log I get](https://github.com/dotnet/docfx/files/946721/report.txt) which contains the full stacktrace at the end.

**Comment by viraln25** [comment]
I am also having same issue with 2.16.2 version - no _site folder created.

**Comment by vicancy** [comment]
@ThomasEnioKohler  @viraln25 v2.16.5 should work, please have a try

**Comment by vicancy** [comment]
@LordZoltan `rezolver-docfx.csproj` is no longer needed, 2.16+ supports the latest csproj.
For the `TypeLoadException`, which version is your docfx? Is it possible that there are multiple version of docfx?
Looks like your `docfx.json` put `properties` in a wrong place...
Yours:
```json
"metadata": [
    {
      "src": [
        {
          "files": [
            "rezolver.csproj"
          ],
          "cwd": "../../src/Rezolver",
          "properties": {
            "TargetFramework": "net46"
          }
        }
      ],
      "dest": "_docfx_proj/obj/api"
    }
  ]
```

Should be:
```json
"metadata": [
    {
      "src": [
        {
          "files": [
            "rezolver.csproj"
          ],
          "cwd": "../../src/Rezolver"
        }
      ],
      "dest": "_docfx_proj/obj/api",
      "properties": {
          "TargetFramework": "net46"
      }
    }
  ]
```

**Comment by ThomasEnioKohler** [comment]
@vicancy I just gave it a try but it still doesn't work. Do I need to do any changes in my configuration because 2.15.5 still works perfect.

**Comment by vicancy** [comment]
@ThomasEnioKohler make sure it is a clean install instead of an update

**Comment by ThomasEnioKohler** [comment]
@vicancy if you mean deinstalling the nuget package and then reinstall this is what I did and it doesn't work. Or do you have another understanding of a clean install?

**Comment by vicancy** [comment]
@ThomasEnioKohler Could you check if your `.csproj` contains such line: `<Import Project="..\packages\docfx.console.2.16.5\build\docfx.console.targets" Condition="Exists('..\packages\docfx.console.2.16.5\build\docfx.console.targets')" />` ?

**Comment by ThomasEnioKohler** [comment]
@vicancy the import line was not available in my project file so I added it. Still doesn't work. So I think the source of my problem is somewhere else. I checke nuget once again and found that there is no version 2.16.5 but only 2.16.2 available and this version is still missing the build folder. Where can I get version 2.16.5?

**Comment by vicancy** [comment]
My fault, I am using myget feed... I pushed the latest bits to nuget, try now.

**Comment by ThomasEnioKohler** [comment]
@vicancy now I got version 2.16.5 but it is still missing the build folder so still not working
![image](https://cloud.githubusercontent.com/assets/25221063/25374523/117c0a94-299e-11e7-93c0-367343f2b4c6.png)

**Comment by LordZoltan** [comment]
@vicancy thanks for taking a look - I struggled to understand how best to migrate my 2.15 json file to 2.16 and thought I'd tried it like that!

I have made the suggested change and my project now builds with the `rezolver.csproj` project; and it's all working again.  That's using 2.16.2 as well (I thought I'd try the latest nuget build rather than download the latest binary release).

Many many thanks for your help!

**Comment by ThomasEnioKohler** [comment]
@vicancy I got 2.16.5 but it sill has no build directory in the package.
![image](https://cloud.githubusercontent.com/assets/25221063/25376500/bf5843fc-29a4-11e7-907e-86b2d606aed5.png)

Isn't this directory needed to make the build work from within Visual Studio 2017?

**Comment by vicancy** [comment]
@ThomasEnioKohler let me check. The `build` directory should be in the package

**Comment by vicancy** [comment]
@ThomasEnioKohler  there is a mysterious bug in .ps script that it occasionally left out the 'build' folder as it contains only one file. Haven't found the root cause yet... Will let you know when 2.16.6 is published.

**Comment by ThomasEnioKohler** [comment]
@vicancy I just found that the target file was copied to the tools directory. So I copied it into the \build folder and rebuilt the documentation. Now I get the following error:
 Build failed.
1>  [17-04-25 01:59:40.370]Error:System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
1>     at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
1>     at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
1>     at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
1>     at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
1>     at Microsoft.DocAsCode.Dfm.DfmEngineBuilder..ctor(Options options, String baseDir, String templateDir, IReadOnlyList`1 fallbackFolders)
1>     at Microsoft.DocAsCode.Dfm.DocfxFlavoredMarked.CreateBuilder(String baseDir, String templateDir, Options options, IReadOnlyList`1 fallbackFolders)
1>     at Microsoft.DocAsCode.Build.Engine.DfmLegacyServiceProvider.DfmService..ctor(String baseDir, String templateDir, ImmutableDictionary`2 tokens, IEnumerable`1 tokenTreeValidator, IReadOnlyList`1 fallbackFolders)
1>     at Microsoft.DocAsCode.Build.Engine.DfmLegacyServiceProvider.CreateMarkdownService(MarkdownServiceParameters parameters)
1>     at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
1>     at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider)
1>     at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
1>     at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
1>     at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
1>     at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
1>     at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
1>     at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
1>  	0 Warning(s)
1>  	1 Error(s)
1>C:\Users\Thomas\.nuget\packages\docfx.console\2.16.5\build\docfx.console.targets(52,5): error MSB3073: The command ""C:\Users\Thomas\.nuget\packages\docfx.console\2.16.5\build\..\tools\docfx.exe" "W:\Net\enio.LockScreenTimer\enio.LockScreenTimer.Documentation/docfx.json" -o "" -l "log.txt" --logLevel "Verbose" -f" exited with code 1.

Any idea?

**Comment by tzachshabtay** [comment]
Oh, this looks like the same issue I talk about here: https://github.com/dotnet/docfx/issues/925, you can try my hack if you want (adding `where !assembly.GetName().FullName.Contains("Microsoft.NuGet.Build.Tasks")` to the linq query in `DfmEngineBuilder.GetContainer`).

**Comment by vicancy** [comment]
Hi @ThomasEnioKohler try the latest one 2.16.7 https://www.nuget.org/packages/docfx.console/

**Comment by ThomasEnioKohler** [comment]
@vicancy Now it builds again. Thank you. The only problem though is that I still get the error written above. Regarding to the post of @tzachshabtay it needs a code change. Could you have a look at this as well?

**Comment by justhoma** [comment]
I've upgraded to the latest version (2.16.7) and everything is now working as expected. Thanks.

**Comment by tzachshabtay** [comment]
The latest version works for me too without that code change (with one caveat: I now need to go to http://localhost:8080/_site instead of http://localhost:8080 to see my site locally).

**Comment by vicancy** [comment]
@ThomasEnioKohler however Microsoft.NuGet.Build.Tasks.dll is not expected to be in the bin path for docfx... could you use FUSLOGVW.exe and provide the Assembly Binding Log https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx?

**Comment by ThomasEnioKohler** [comment]
@vicancy There were the following binding errors:

Microsoft.Build.resources, Version=15.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a.HTM (2 hits)
	Line 5: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 37: Bind result: hr = 0x80070002. The system cannot find the file specified.

Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a.HTM (2 hits)
	Line 5: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 37: Bind result: hr = 0x80070002. The system cannot find the file specified.

Microsoft.Build.Utilities.Core, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.HTM (3 hits)
	Line 5: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 48: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 91: Bind result: hr = 0x80070002. The system cannot find the file specified.

Microsoft.CodeAnalysis.Workspaces.Desktop.resources, Version=2.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35.HTM (2 hits)
	Line 5: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 37: Bind result: hr = 0x80070002. The system cannot find the file specified.

Microsoft.CodeAnalysis.Workspaces.Desktop.resources, Version=2.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35.HTM (2 hits)
	Line 5: Bind result: hr = 0x80070002. The system cannot find the file specified.
	Line 37: Bind result: hr = 0x80070002. The system cannot find the file specified.

**Comment by vicancy** [comment]
Thanks @ThomasEnioKohler I am closing this issue as it is fixed and using #925 to track the TypeLoadException issue.
