### ISSUE TITLE
Wrong metadata generation for Netstandard assemblies

### ISSUE THREAD

**Issue by SavchenkoAlexander** [dotnet/docfx#2387]
**DocFX Version Used**: 2.30

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1. Create VS Project for ClassLibrary (Target framework: Netstandard 2.0)
2. Define any Enum.
3. Build metadata with docfx for resulting dll.

**Expected Behavior**:
Type for Enum - Enum.
**Actual Behavior**:
Type for Enum - Class.

**Comment by vicancy** [comment]
Reproduced. This happens when `docfx metadata a.dll`, `docfx metadata a.csproj` works fine.

**Comment by vicancy** [comment]
It turns out that system.object is not successfully resolved with assemblies and thus the enum turns out to be an ErrorType and fallback to default value `Class`

**Comment by Skudnoff** [comment]
Is there any progress with this issue? Or may be some workaround?

**Comment by vicancy** [comment]
Currently docfx by default loads `mscorlib.dll` to resolve `system.object`, however, for `netcore` cases, `mscorlib.dll` may not exists, and thus `system` classes are not able to be found. To fix this issue, we need to support `netcore` environment for assembly loadings. Adding @superyyrrzz and @herohua to take a look at the issue.

**Comment by SavchenkoAlexander** [comment]
The same behavior was reproduced for delegates.

**Comment by Herrmel** [comment]
Is there any Update on this as I'm facing the same problem for my dll's. Or will this be addressed with release v3?

**Comment by hermann-noll** [comment]
Unfortunately this is still an issue with the current version.

**Comment by Herrmel** [comment]
Yeah I had to do a workaround myself. I compiled a Version without the line where the wrong .net-Assembly is loaded and added the correct .net core assemblies via paths in the docfx.json property references. I tried to add a automatic way to resolve all needed Assemblies but its pretty hard and I gave up at some point. The closest I got was with some help of the Nuget from ILSpy but it did not always find the correct version of the framework.
Though part of why I gave up was that I also tried to fix inheritdocs from external dll's at the same time. For example when you inherit documentation from System-Types it currently is not able to resolve those and leaves them empty.
Back then I was hoping for docfx v3 to release for community soon but I'm still waiting without any releasenews in sight.

**Comment by KrestenHelstrup** [comment]
Any updates or workarounds on this issue ?
Will it be fixed in v3 ?

**Comment by KrestenHelstrup** [comment]
@yufeih - I see you closed the issue, however I don't think the bug is fixed. At least I still get the same behavior with docfx version 2.61.0 and a class library .netstandard 2.0.

**Comment by yufeih** [comment]
Yes I can also repo this as well. I might have accidentally deleted this assuming it was building from `csproj`.

**Comment by KrestenHelstrup** [comment]
@yufeih - Thanks for resolving the issue. When can we expect a 2.61.1 released with this fix included ?
