### ISSUE TITLE
xref and cref not working for some BCL types

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docfx#2646]
The majority of BCL types work when used in xref in markdown and cref in /// comments, but some don't, even though xrefservice returns information for them.

**DocFX Version Used**: 2.34

**Template used**: `default`

**Steps to Reproduce**:

1. Set up docfx.json for BCL xrefs (ie "xrefService": [ "https://xref.docs.microsoft.com/query?uid={uid}" ])

2. Use the xref in a markdown article:
```
- <xref:System.Object>
- <xref:System.Int32>
- <xref:System.Data.SqlClient>
- <xref:System.Data.SqlDbType>
- <xref:System.Data.DbType.Int32>
- <xref:System.IComparable>
```

3. Use the cref in a /// comment:
```
    /// <summary>
    /// <para><see cref="System.Object"/></para>
    /// <para><see cref="System.Int32"/></para>
    /// <para><see cref="System.Data.SqlClient"/></para>
    /// <para><see cref="System.Data.SqlDbType"/></para>
    /// <para><see cref="System.Data.DbType.Int32"/></para>
    /// <para><see cref="System.IComparable"/></para>
    /// </summary>
```
3. Generate the HTML and look at the website

**Expected Behavior**:

All the xref & cref shows up correctly, with the correct hyperlinks.

**Actual Behavior**:

Only "System.Object" works in both markdown and /// comments, but none of the other references work in either markdown (showing `<xref:System.Int32>` etc.) or /// comments (showing `System.Int32` etc.)

In api/*.yml, the failing types etc. are missing attributes:
```
references:
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  commentId: T:System.Int32
- uid: System.Data.SqlClient
  commentId: N:System.Data.SqlClient
- uid: System.Data.SqlDbType
  commentId: T:System.Data.SqlDbType
- uid: System.Data.DbType.Int32
  commentId: F:System.Data.DbType.Int32
- uid: System.IComparable
  commentId: T:System.IComparable
```

**Comment by fubar-coder** [comment]
The problem also occurs in the FluentMigrator documentation:

https://github.com/fluentmigrator/documentation

**Comment by fubar-coder** [comment]
@vwxyzh IMHO The problem was caused by a change of the uid generation which was meant to simplify a signature when - for example - a function and its parameter are from the same namespace. I guess what bit us here, was a too eager simplification of the interface implemented by a class.

**Comment by vwxyzh** [comment]
@KristianWedberg is it fixed in v2.36?

**Comment by KristianWedberg** [comment]
No, they still don't work in v2.36.1.

**Comment by KristianWedberg** [comment]
@vwxyzh 

This still doesn't work in v2.37.1, is there any timeline for when it will be fixed?

Thanks.

**Comment by KristianWedberg** [comment]
Still not working in v2.39.2.

**Comment by TheSatoshiChiba** [comment]
Are there any updates on this?

**Comment by KristianWedberg** [comment]
Still not working in v2.40.7, any update on this?

**Comment by superyyrrzz** [comment]
@KristianWedberg I just tried it but cannot reproduce this issue. Could you provide detailed reproduce steps or a sample repository to reproduce this?

**Comment by fubar-coder** [comment]
Is this really fixed? I remember seeing this problem in 2.43.2.0.

**Comment by superyyrrzz** [comment]
@fubar-coder @rmsy I guess what you are experiencing is not same as the original issue. My former test cannot reproduce the issue. Your detailed repro steps can help move this issue forward. Ideally, a repo with docfx.json with minimal content is most helpful.

**Comment by fubar-coder** [comment]
It's difficult, because it only happens sometimes. At first, it works fine. Then you update the documentation and all BCL types aren't found/linked anymore. There is a chance - if you make even more changes - that everything will work again, but I'll try to create a repro.

**Comment by KristianWedberg** [comment]
I have the same experience - some BCL references start to fail in a large docfx project, and cleaning + rebuilding doesn't help. A new project with a near-identical docfx.json and the same BCL types will, however, work OK.

**Comment by JimBobSquarePants** [comment]
Can we please reopen this issue? There are still BCL type that will not resolve in v2.5.2
