### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by smaillet** [dotnet/docfx#5554]
**Operating System**:  Windows
**DocFX Version Used**:  2.42.2
**Template used**:  `statictoc` with custom [Though not relevant as the error happens before templates come into play
**Steps to Reproduce**:
1.  Rundocfx in an automated build on APPVEYOR or GitHub Actions with only VS2019
2.  [Full APPVEYOR LOGS With Verbose DocFX output](https://ci.appveyor.com/api/buildjobs/ttw8qe3e2emb1te0/log)
    1. The logs include dump of env vars, path var details, VS instance and MSbuild location and version. (None of which seems out of the ordinary in comparison to local builds that work...)

**Expected Behavior**:
Should work same as it does locally the actual code files build and produce testatble binaries that pass all tests.
**Actual Behavior**:
Code builds fine, but DOCFX blows up with 'The SDK 'Microsoft.NET.Sdk' specified could not be found.' This is 100% repro on both GH Actions and AppVeyor, making it impossible to do automated build and update of docs.

Worse is that it logs "warnings" and doesn't actually consider the issue to be a fail - even though it is a total fail for generating docs based on current source.

To leverage C#8 and SDK3 the Global.JSON was recently updated to 
```json
{
    "sdk": {
        "version": "3.1.100",
        "rollForward": "latestMajor"
    },
    "msbuild-sdks": {
        "Microsoft.Build.NoTargets": "1.0.53",
        "Microsoft.Build.CentralPackageVersions": "2.0.36"
    }
}
```

This is when DOCFX started to fall over, Somehow it's internal MSBUILD is used in a way that it can't correctly find the SDK.

This would appear to be related to multiple other issues closed as no repro, however this is a 100% repro case. [#5144, #4880, #4471] all of which were closed without a real resolution.

**Comment by smaillet** [comment]
NOTE: Uninstalling VS2017 from my local machine will trigger the problem, even on my previously working build - seems like something in DOCFX has a hard coded assumption of VS2017 and doesn't work without it.

**Comment by superyyrrzz** [comment]
It may need to upgrade `Microsoft.CodeAnalysis.*` packages.

**Comment by jspuij** [comment]
Same here.

**Comment by Dollab** [comment]
We encounter the same issue.

**Comment by SteveDinn** [comment]
I'm encountering this now while attempting to build a .NET Core 3.1 project in VS 2019.

**Comment by smaillet** [comment]
I managed to workaround it by adding  "allowPrerelease" : false to the global.json. My settings now looks like:

```json
{
    "sdk": {
        "version": "3.1.101",
        "rollForward": "latestMajor",
        "allowPrerelease" : false
    },
    "msbuild-sdks": {
        "Microsoft.Build.NoTargets": "1.0.53",
        "Microsoft.Build.CentralPackageVersions": "2.0.36"
    }
}
```

**Comment by SteveDinn** [comment]
Since I'm running through Visual Studio, I think I have this already set to false by having the option unchecked in Tools\Options\Environment\Preview Features. I haven't changed any values in that section.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x
> If you don't set this value explicitly, the default value depends on whether you're running from Visual Studio:
> * If you're **not** in Visual Studio, the default value is true.
> * If you are in Visual Studio, it uses the prerelease status requested. That is, if you're using a preview version of Visual Studio or you set the **Use previews of the .NET Core SDK** option (under **Tools** > **Options** > **Environment** > **Preview Features**), the default value is `true`; otherwise, false.

![image](https://user-images.githubusercontent.com/3911507/85306701-3faa5900-b485-11ea-8f20-47d692a7c612.png)

**Comment by smaillet** [comment]
Sadly, this issue remains. I have a different project that was updated to targeting netstandard2.1 and net5.0, an I continue to get this error. I've tried all manner of variations on the Global.json, but nothing works. This is yet another bug in docfx that's not getting any attention or fix. Seems like docfx has gone dead from my view. The promised V3 has been in a development state ofr nearly 2 years now and we aren't seeing much in the way of traction or resolution to the issues in the current release. I've lost count of the number of workarounds I've had to make for docfx bugs - and the one I found previously for this doesn't work anymore in this case.

**Comment by v-pegao** [comment]
@smaillet This issue seems have been resolved in latest version docfx(version = 2.56.6), would you please try the latest version docfx?

Here are GitHub Action build results with `docfx.2.42.2` and `docfx.2.56.6`
| Docfx Version | Build Result With Build Link |
| --- | --- |
| 2.42.2 | [Docfx throws warning 'Microsoft SDK not found ' and no doc is generated](https://github.com/v-pegao/test/actions/runs/613268081) |
| 2.56.6 | [Docfx build succeeds with no warning and docs are generated](https://github.com/v-pegao/test/actions/runs/613270727) | 

---
If you met the issue with latest docfx, would you please help provide an small docfx_project or other details that can help reproduce/catch the issue? That will be help a lot to resolve the issue. Thanks in advance!

cc @superyyrrzz

**Comment by mikernet** [comment]
@v-pegao This is still happening on docfx latest dev branch build. You can clone [this repo](https://github.com/Singulink/Singulink.Numerics.BigDecimal) and run docfx in the `Docs` directory.

**Comment by mikernet** [comment]
It stopped working for all my projects, can't build docs for any of them.

**Comment by v-pegao** [comment]
@mikernet Looks like it's related to the local environment. Here are some info of my local machine that cannot repro the issue for your reference:
- Visual Studio Version:
![image](https://user-images.githubusercontent.com/25164547/116513567-61256e00-a8fc-11eb-8928-1885243e4cd4.png)
- Installed dotnet sdks:
![image](https://user-images.githubusercontent.com/25164547/116513590-697da900-a8fc-11eb-93dc-a9bb252b0d1c.png)
- `MSBuildSDKsPath` is not specified in my system environment variables.


Here is the github action I setup to build docs for your repo on windows-latest machine, it works fine. You can check the detailed environment info and build output in build result.
 [Github action](https://github.com/v-pegao/test/blob/test-docfx-dev-9b33de5/.github/workflows/docfx-build.yml) => [Build result](https://github.com/v-pegao/test/actions/runs/795192068)

**Comment by mikernet** [comment]
Everything else except docfx works fine though, so not really sure where to go from here.

**Comment by jamiehankins** [comment]
For what it's worth, I started seeing this when I modified my VS installation. I unchecked "Windows 10 SDK (10.0.17763.0)" because I have "Windows 10 SDK (10.0.18362.0)". It seems stupid to have multiple versions of the platform SDK.

So the message "The SDK 'Microsoft.NET.Sdk' specified could not be found." may not be strictly accurate. It might be looking for the wrong platform SDK.

I just tried adding that SDK back, and alas, it didn't help. I also updated my Visual Studio to 16.10.0. That could be the change that did this.

We depend on this working, so I really hope I find a solution short of burning down my dev machine and rebuilding.

**Comment by jamiehankins** [comment]
This resolved it, at least for us.
https://github.com/dotnet/docfx/pull/7384#pullrequestreview-669710062

**Comment by patware** [comment]
For what it's worth, for me, I had VS2019Ent and VS2019Ent Preview, and the problem started when I uninstalled VS2019Ent Preview.  I re-installed VS2019Ent...  still the same problem.

If I run msbuild on the sln, no problem.  The problem only occurs with docfx.

**Comment by jamiehankins** [comment]
> For what it's worth, for me, I had VS2019Ent and VS2019Ent Preview, and the problem started when I uninstalled VS2019Ent Preview. I re-installed VS2019Ent... still the same problem.
> 
> If I run msbuild on the sln, no problem. The problem only occurs with docfx.

Have you tried the newest DocFX from a few days ago? This is fixed in it.

**Comment by patware** [comment]
Perfect !!!  That did it.  Chocolatey is still at 2.57.2 so I copied the latest release [2.58 from github](https://github.com/dotnet/docfx/releases/tag/v2.58) over the bits in my local choco path and it worked.

I noticed that the DocFx extension in Azure DevOps pipelines don't use chocolatey but uses NuGet to fetch the latest ```nuget.exe install docfx.console``` 

In the future, should I be using nuget's docfx.console package or chocolatey's docfx package ?

**Comment by jamiehankins** [comment]
Nuget is directly populated by the Github releases. That's what I use.

________________________________

**Comment by superyyrrzz** [comment]
2.58 now is also released on chocolatey.

**Comment by FLAMESpl** [comment]
I am still experiencing this issue on 2.59 as well as on 2.58.
Getting:
```
[22-02-15 12:45:23.832]Warning:[MetadataCommand.ExtractMetadata](C:/EUVIC/acproject/backend-workflows/AboveCloud/src/AboveCloud.Workflows.Contracts/AboveCloud.Workflows.Contracts.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\EUVIC\acproject\backend-workflows\AboveCloud\src\AboveCloud.Workflows.Contracts\AboveCloud.Workflows.Contracts.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\EUVIC\acproject\backend-workflows\AboveCloud\src\AboveCloud.Workflows.Contracts\AboveCloud.Workflows.Contracts.csproj
```
Target framework of this project is `net5.0` and my global.json is 
```
{
  "projects": [ "src", "tools" ],
  "sdk": {
    "version": "5.0.404"
  }
}
```
My installed sdks:
```
3.1.201 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
```

**Comment by groogiam** [comment]
I am experiencing this with 2.59.4.
