### ISSUE TITLE
Assertion failure in 2.5.2

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#719]
This is using 2.5.2 from the zip file, against a dotnet cli project. (It's not fully clear to me whether that's supported, but at least the result could be prettier...)

Running `docfx metadata -f path/to/docfx.json` I get a Watson screen as below:

![docfx assertion](https://cloud.githubusercontent.com/assets/17011/18628736/863bb064-7e59-11e6-9968-284cd61dd98a.png)

Two problems:

- I have no idea what the failure is here
- Coming up as an assertion failure window rather than an error appearing on the console is worrying; I don't know what would happen if this occurred in CI, for example. (It also means I can't copy/paste the text etc.)

The same project works fine in 2.4, btw.

**Comment by vwxyzh** [comment]
Only 4 commit is related from v2.4:
Update to support .NET Core (#656) 821dd491053cd50a722340b0634c579ecb551406
Add information for metadata fail. (#665) 6d18d0a4eb660f925c4c33e42973ae8efd26a39a
update documentation for attribute filter (#686) ef2c13638225df0470111c689c02b1e72a4435c9
Remove *.csproj and packages.config (#706) f8b394520bc4cabd27e84f90a7a78f65ba6834a9

**Comment by jskeet** [comment]
Hmm. I'll try with the zip files from each of the releases then (2.4.0, 2.5.0, 2.5.1) to see where it came from. I was using DNX for 2.4.0, so I don't know whether there's a significant difference in the code there...

**Comment by vwxyzh** [comment]
We found something wrong in project.json:
```json
    "Release": {
      "buildOptions": {
        "define": [ "DEBUG", "TRACE" ],
        "optimize": true
      }
    }
```
@qinezh Release build should not contain `DEBUG`.

**Comment by qinezh** [comment]
The issue should fixed in latest release DocFX.

**Comment by jskeet** [comment]
Nope, I'm afraid I still get the same assertion failure with 2.5.3 :(

**Comment by nothrow** [comment]
I have reproducible sample here. For me, issue reproduces when I have interface method with template, and in implementation there is also `/// <summary>`.

Steps to reproduce:

`docfx init -q`

docfx.json:
```
{
"metadata": [
    {
      "src": [
        {
          "files": [
            "src/*.cs"
          ], ... 
```

add to `src\` following:

IInterface.cs:

```
namespace A {
  public interface IInterface
  {
    /// <summary>
    /// Summary
    /// </summary>
    void Function<T>();
  }
}
```

Implementation.cs:

```
namespace A {
  public class Implementation : IInterface
  {
    /// <summary>
    /// Summary
    /// </summary>
    public void Function<T>()
    {
    }
  }
}
```

2.5.3 version.

**Comment by qinezh** [comment]
The issue may caused by that `dotnet publish` also need specify build configuration

**Comment by qinezh** [comment]
[New release](https://github.com/dotnet/docfx/releases/tag/v2.5.4) updated

**Comment by jskeet** [comment]
Hooray - this does seem to have fixed it, thanks.

**Comment by qinezh** [comment]
@jskeet great to hear that 😄 

@nothrow Thank you to repro it, we will fix the case later. BTW, could you open a pull request to include the unit test? It seems worth to add it in DocFX.

**Comment by nothrow** [comment]
@qinezh, https://github.com/dotnet/docfx/pull/728

Just one comment: I think that the fix in v2.5.4 just hides the issue. It was not regression, I reproduced the issue even before v2.5.2, when compiled with `DEBUG`.

My .02$ advice would be - don't use `Debug.Assert`, just throw, even in release, or lot of problems may be there left unnoticed.

**Comment by qinezh** [comment]
`Debug.Assert` in this case is by design as I know, @vwxyzh Could you explain it to @nothrow ?
